-- Auto-generated from schema-map-postgres.psd1 (map@mtime:2025-11-21T00:25:46Z)
-- engine: postgres
-- table:  tax_rates

CREATE TABLE IF NOT EXISTS tax_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_iso2 CHAR(2) NOT NULL,
  category TEXT NOT NULL,
  rate NUMERIC(5,2) NOT NULL,
  valid_from DATE NOT NULL,
  valid_to DATE NULL,
  CONSTRAINT chk_tax_category CHECK (category IN ('ebook','physical')),
  CONSTRAINT chk_tax_valid_span CHECK (valid_to IS NULL OR valid_to >= valid_from)
);
