-- Auto-generated from schema-map-postgres.yaml (map@sha1:8C4F2BC1C4D22EE71E27B5A7968C71E32D8D884D)
-- engine: postgres
-- table:  tax_rates

CREATE TABLE IF NOT EXISTS tax_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_iso2 CHAR(2) NOT NULL,
  category TEXT NOT NULL,
  rate NUMERIC(5,2) NOT NULL,
  valid_from DATE NOT NULL,
  valid_to DATE NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_tax_category CHECK (category IN ('ebook','physical')),
  CONSTRAINT chk_tax_valid_span CHECK (valid_to IS NULL OR valid_to >= valid_from)
);
